apiVersion: apps/v1
kind: Deployment
metadata:                       # Place the namespace here
  name: docker-deployment
  namespace: jenkins-ci-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-deployment
  template:
    metadata:
      labels:
        app: docker-deployment
    spec:
      containers:
      - name: docker-deployment
        image: suryaloganathan/nginx-docker
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: docker-service
  namespace: jenkins-ci-cd          # Include namespace here as well
spec:
  selector:
    app: docker-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
